###########################################################################################
# Configuration file for the Control Flow Fuzzer.                                         #
###########################################################################################

# ===== Logging ===========================================================================

# Level of error at which the log should be written. Default value is INFO.
# Levels are explained as follow:
# - TRACE: Logs every single execution details (like packets and their contents)
#          Be wary that this log level is extremely verbose and generate a great
#          amount of information. It should be used only when strictly necessary
# - DEBUG: Logs every debug information.
# - INFO:  Standard log information.
# - WARN:  Logs only error and warning messages.
# - ERROR: Logs only the error messages.

# Log level of the logfile. Default to "INFO".
FileLogLevel INFO
# log information displayed in the console. Default to "WARN".
ConsoleLogLevel WARN

# Keep a trace of the packet captured if "KeepPacketTrace" is set to Yes|True.
# The network interface used for the packet capture must also be specified with
# the parameter "NIC".
KeepPacketTrace No
PcapFilter "openflow_v5"
NIC eth0

# ===== SDN Controller ====================================================================
# IP address used by the controller
SDNControllerIP 127.0.0.1
 # Port used by the SDN switches. Default to "6653"
SDNControllerOpenflowPort 6653
# Port used to connect to the Northbound API. Default to "8181"
SDNControllerRestPort 8181
# User name to connect to the Northbound API. Default to "onos"
SDNControllerUser "onos"
# Password used to connect to the Northbound API. Default to "rocks"
SDNControllerPassword "rocks"
# File path to the SDN Controller log path. Default to "/opt/onos/karaf/data/log/karaf.log"
SDNControllerLogPath "/opt/onos/karaf/data/log/karaf.log"

# ===== SDN switch ========================================================================
# IP address used by the SDN switch
SDNSwitchIP 127.0.0.1
# Port used by the SDN Switch to connect to the controller
SDNSwitchPort 52525
# Version of the Openflow protocol used by the SDN switch
OpenflowVersion 1.4

# ===== MySQL Database ======================================================================
# Host of the MySQL server
MySqlHost "127.0.0.1"
# Port used by MySQL server
MySqlPort 3306
# Username to be used by the application
MySqlUser "ControlFlowFuzzer"
# Password to be used by the application. Default to rocks
MySqlPassword "rocks"