#!/bin/bash
# ----------------------------------------------------------------------------------------------------------------------
# Remotely stops & uninstalls ONOS on the specified node.
# ----------------------------------------------------------------------------------------------------------------------

# move to script directory
cd "$(dirname "$0")" || exit
# Load onos-env script
source ./onos-env

sudo service onos stop  1>/dev/null 2>/dev/null
# Wait for onos to stop up to 5 seconds
for i in $(seq 1 5); do
  [ -z "$(ps -ef | grep org.apache.karaf.main.Main | grep -v grep)" ] && break
  sleep 1
done

[ -z "$(ps -ef | grep org.apache.karaf.main.Main | grep -v grep)" ] || (echo 'ONOS failed to stop.'; status=1)

# Remove onos directory and init file
[ -d "${ONOS_INSTALL_DIR}" ] && sudo rm -fr "$ONOS_INSTALL_DIR"
[ -f /etc/init/onos.conf ] && sudo rm -f /etc/init/onos.conf
[ -f /etc/init.d/onos ] && sudo rm -f /etc/init.d/onos
[ -f /etc/systemd/system/onos.service ] && sudo rm -f /etc/systemd/system/onos.service

exit ${status:-0}
